import Head from "next/head";
import Image from "next/image";

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <nav>
          <a href="/">Home </a>
          <a href="/events">Events </a>
          <a href="/about">About </a>
        </nav>
      </header>
      <main>
        {data.map((ev) => (
          <a key={ev.id} href={`/events/${ev.id}`}>
            <Image width={100} height={200} alt={ev.title} src={ev.image} />
            <h2> {ev.title} </h2>
            <p>{ev.description}</p>
          </a>
        ))}
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const { events_categories } = await import("../data/data.json");

  return {
    props: {
      data: events_categories,
    },
  };
}
